# TASK 1
dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

In [1]:
import pandas as pd

df = pd.read_csv('vgsalesGlobale.csv')
df.head()

Rank                      Name Platform    Year         Genre Publisher  \
0     1                Wii Sports      Wii  2006.0        Sports  Nintendo   
1     2         Super Mario Bros.      NES  1985.0      Platform  Nintendo   
2     3            Mario Kart Wii      Wii  2008.0        Racing  Nintendo   
3     4         Wii Sports Resort      Wii  2009.0        Sports  Nintendo   
4     5  Pokemon Red/Pokemon Blue       GB  1996.0  Role-Playing  Nintendo   

   NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales  
0     41.49     29.02      3.77         8.46         82.74  
1     29.08      3.58      6.81         0.77         40.24  
2     15.85     12.88      3.79         3.31         35.82  
3     15.75     11.01      3.28         2.96         33.00  
4     11.27      8.89     10.22         1.00         31.37

In [2]:
total_global_sales = df['Global_Sales'].sum()
print(f'Total Global sales is {total_global_sales}')

Total Global sales is 8920.44


In [3]:
game_with_highest_sale = df[df['Global_Sales'] == df['Global_Sales'].max()]
print(f'Game with highest sale is {game_with_highest_sale["Name"].values[0]}')


Game with highest sale is Wii Sports


In [4]:
average_sales_for_each_region = df[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].mean()
print(f'Average sales for each region are {average_sales_for_each_region}')

Average sales for each region are NA_Sales       0.264667
EU_Sales       0.146652
JP_Sales       0.077782
Other_Sales    0.048063
dtype: float64


In [5]:
top_5_most_popular_games = df.sort_values(by='Global_Sales', ascending=False).head(5)
print(f'Top 5 most popular games are {top_5_most_popular_games["Name"].values}')

Top 5 most popular games are ['Wii Sports' 'Super Mario Bros.' 'Mario Kart Wii' 'Wii Sports Resort'
 'Pokemon Red/Pokemon Blue']


In [6]:
total_sales_for_each_genre_in_each_region = df.groupby('Genre')[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].sum()
print(f'Total sales for each genre in each region are {total_sales_for_each_genre_in_each_region}')

popular_genre_in_NA = df.groupby('Genre')['NA_Sales'].sum().idxmax()
print(f'Most popular genre in North America is {popular_genre_in_NA}')

Total sales for each genre in each region are               NA_Sales  EU_Sales  JP_Sales  Other_Sales
Genre                                                  
Action          877.83    525.00    159.95       187.38
Adventure       105.80     64.13     52.07        16.81
Fighting        223.59    101.32     87.35        36.68
Misc            410.24    215.98    107.76        75.32
Platform        447.05    201.63    130.77        51.59
Puzzle          123.78     50.78     57.31        12.55
Racing          359.42    238.39     56.69        77.27
Role-Playing    327.28    188.06    352.31        59.61
Shooter         582.60    313.27     38.28       102.69
Simulation      183.31    113.38     63.70        31.52
Sports          683.35    376.85    135.37       134.97
Strategy         68.70     45.34     49.46        11.36
Most popular genre in North America is Action


In [7]:
df.tail(10)

Rank                                               Name Platform  \
16588  16591                                   Mega Brain Boost       DS   
16589  16592  Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...      PSV   
16590  16593  Eiyuu Densetsu: Sora no Kiseki Material Collec...      PSP   
16591  16594                                Myst IV: Revelation       PC   
16592  16595                                           Plushees       DS   
16593  16596                 Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                      Men in Black II: Alien Escape       GC   
16595  16598   SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                         Know How 2       DS   
16597  16600                                   Spirits & Spells      GBA   

         Year         Genre              Publisher  NA_Sales  EU_Sales  \
16588  2008.0        Puzzle  Majesco Entertainment      0.01      0.00   
16589  2016.0        Action        dramatic create      0.00      0.00   
16590  2007.0  Role-Playing     Falcom Corporation      0.00      0.00   
16591  2004.0     Adventure                Ubisoft      0.01      0.00   
16592  2008.0    Simulation              Destineer      0.01      0.00   
16593  2002.0      Platform                  Kemco      0.01      0.00   
16594  2003.0       Shooter             Infogrames      0.01      0.00   
16595  2008.0        Racing             Activision      0.00      0.00   
16596  2010.0        Puzzle               7G//AMES      0.00      0.01   
16597  2003.0      Platform                Wanadoo      0.01      0.00   

       JP_Sales  Other_Sales  Global_Sales  
16588      0.00          0.0          0.01  
16589      0.01          0.0          0.01  
16590      0.01          0.0          0.01  
16591      0.00          0.0          0.01  
16592      0.00          0.0          0.01  
16593      0.00          0.0          0.01  
16594      0.00          0.0          0.01  
16595      0.00          0.0          0.01  
16596      0.00          0.0          0.01  
16597      0.00          0.0          0.01

In [8]:
top_3_platforms = df.groupby('Platform')['Global_Sales'].sum().sort_values(ascending=False).head(3)
print(f'Top 3 platforms are {top_3_platforms}')

Top 3 platforms are Platform
PS2     1255.64
X360     979.96
PS3      957.84
Name: Global_Sales, dtype: float64


In [9]:
market_share = df.groupby('Genre')['Global_Sales'].sum() / total_global_sales * 100
print(f'Market share for each genre is {market_share}')

Market share for each genre is Genre
Action          19.631094
Adventure        2.679688
Fighting         5.032375
Misc             9.079821
Platform         9.319832
Puzzle           2.745941
Racing           8.206322
Role-Playing    10.396012
Shooter         11.629135
Simulation       4.396644
Sports          14.920004
Strategy         1.963132
Name: Global_Sales, dtype: float64


In [10]:
correlation = df['NA_Sales'].corr(df['EU_Sales'])
print(f'Correlation between North America and Europe sales is {correlation}')

Correlation between North America and Europe sales is 0.767726748370264


## Task 2 English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [11]:
eng_to_span = {
    'stop': 'detener',
    'word': 'palabra',
    'deep': 'profundo',
    'seek': 'buscar',
    'chat': 'charla',
    'crazy': 'loco',
    'courage': 'coraje',
    'brave': 'valiente',
    'fear': 'miedo',
    'fright': 'susto'
}

while(True):
    get_word = input("Enter a word of english for translation: ")
    if get_word in eng_to_span:
        print(f'The spanish translation of {get_word} is {eng_to_span[get_word]}')
    else:
        print(f'The word {get_word} is not in the dictionary')
    if input('Do you want to continue? (y/n): ') == 'n':
        break

The word hello is not in the dictionary



## Task 3 Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [12]:
def classify_emails(emails):
    important = []
    spam = []
    promotions = []
    
    promotions_keywords = ["exclusive", "limited time", "discount", "special offer", "free", "upgrade", "bonus", "alert", "today", "limited availability", "early access", "VIP", "insider", "new", "sale", "save", "don't miss out", "act now", "countdown", "flash sale", "gift", "reward", "opportunity", "limited edition", "guaranteed", "secure", "instantly", "click here", "explore", "discover", "unmissable", "must-have"]
    important_keywords = ["urgent", "action required", "time-sensitive", "priority", "critical", "please review", "follow up", "need your attention", "deadline", "update", "confirmation", "decision needed", "confidential", "sensitive information", "next steps", "immediate response" ]
    spam_keywords = ["viagra", "nigeria", "prince", "million dollars", "money", "bank account", "online pharmacy", "free", "click here", "check this out", "visit our website", "you're a winner", "congratulations", "lottery", "inheritance", "urgent", "limited time", "offer", "dear"]
    for email in emails:
        for keyword in promotions_keywords:
            if keyword in email:
                promotions.append(email)
                break
        for keyword in important_keywords:
            if keyword in email:
                important.append(email)
                break
        for keyword in spam_keywords:
            if keyword in email:
                spam.append(email)
                break
    return important, spam, promotions

emails = ["action required", "Congratulations! You've won a FREE iPad! Click here to claim your prize", "Please review the attached report and provide feedback by EOD", "URGENT: Action Required. Your account will be suspended", "Exclusive offer! Buy one get one free. Limited time only", "Dear valued customer, please take a moment to review our products", "You're a winner! Claim your prize today", "Limited time offer. Click here to explore", "Viagra on sale now. Get 50% off on your first purchase", "Check out our new arrivals. Click here to explore", "Your bank account has been compromised. Click here to secure your account"]
important, spam, promotions = classify_emails(emails)
print(f'Important emails are {important}')
print(f'Spam emails are {spam}')
print(f'Promotions emails are {promotions}')


Important emails are ['action required']
Spam emails are ['Exclusive offer! Buy one get one free. Limited time only', 'Limited time offer. Click here to explore', 'Your bank account has been compromised. Click here to secure your account']
Promotions emails are ['Exclusive offer! Buy one get one free. Limited time only', "You're a winner! Claim your prize today", 'Limited time offer. Click here to explore', 'Viagra on sale now. Get 50% off on your first purchase', 'Check out our new arrivals. Click here to explore', 'Your bank account has been compromised. Click here to secure your account']


## Task 4 Online Store Shopping Cart
Write a Python program to simulate the online store's shopping cart system. The program should use a while loop to provide an interactive shopping experience.


### Tasks:
* Initialize an empty list called shopping_cart to store items.
* Display a welcome message and available products.
* Loop should be iterating over AI Response Simulator and Investment decision and keep asking for user input.
* Prompt the user to enter the number corresponding to the product they want to add to the cart.
* Check if the user entered 'q'. If so, break the loop.
* Convert the choice to an integer and validate it within the valid range (1 to 3).
* Based on the user's choice, add the selected product to the shopping_cart list.
* Display a confirmation message indicating the added product.
* Continue the loop to allow the user to add more products or proceed to checkout.
* After the loop ends, display the contents of the shopping cart.
* Display a goodbye message.
* End the program.

In [17]:
shopping_cart = []
available_products = {
    1: 'Nvidia RTX 4090',
    2: 'Hyper X 16 GB 3200MHz Rams',
    3: 'Thunder 650 Watt PSU',
    4: 'RGB Casing',
    5: 'Logitech g102'
}
print('Welcome to the shopping cart!')
print('Available products are:')
for serial_no, product in available_products.items():
    print(f'{serial_no}: {product}')
    
while(True):
    product = int(input('Enter the product number you want to add to the cart: '))
    if product in available_products:
        shopping_cart.append(available_products[product])
    else:
        print('Product not available')
    if input('Do you want to exit? Press (q): ').lower() == 'q':
        break
    
print(f'Your cart contains: {shopping_cart}')
print("Goodbye!")


Welcome to the shopping cart!
Available products are:
1: Nvidia RTX 4090
2: Hyper X 16 GB 3200MHz Rams
3: Thunder 650 Watt PSU
4: RGB Casing
5: Logitech g102
Your cart contains: ['Nvidia RTX 4090', 'Hyper X 16 GB 3200MHz Rams']
Goodbye!


## Task 5
* Create two NumPy arrays of the same shape and perform element-wise addition on them.
* Calculate the element-wise product of two NumPy arrays.

In [14]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([4, 5, 6, 7, 8])

addition = arr1 + arr2
multiplication = arr1 * arr2
print(f"Addition of two arrays: {addition}")
print(f"Multiplication of two arrays: {multiplication}")

Addition of two arrays: [ 5  7  9 11 13]
Multiplication of two arrays: [ 4 10 18 28 40]


## Task 6
* Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

* Concatenate two NumPy arrays horizontally and vertically.

In [15]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]).reshape(3,4)
print(f'Reshapes array: {arr.shape}')
print(arr)

horizontal_concatenation = np.hstack((arr1, arr2))
print(f'Horizontally contactenated array is {horizontal_concatenation}')

vertical_concatenation = np.vstack((arr1, arr2))
print(f'Vertically concatenated array is {vertical_concatenation}')

Reshapes array: (3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Horizontally contactenated array is [1 2 3 4 5 4 5 6 7 8]
Vertically concatenated array is [[1 2 3 4 5]
 [4 5 6 7 8]]


## Task 7
* Reverse A List In Python Using Slicing


In [16]:
lisssttt = [1,2,3,4,5,6,7,8]
reveresed = lisssttt[::-1]
print(f'List: {lisssttt}')
print(f'Reversed list: {reveresed}')

List: [1, 2, 3, 4, 5, 6, 7, 8]
Reversed list: [8, 7, 6, 5, 4, 3, 2, 1]


# TASK 8
You need to download the GitHub Desktop software, push your lab task to your GitHub account, and share the link on GCR as a submission.